### ISSUE TITLE
Goldelox_Serial_4DLib.cpp needs to stop port flushing for SAM/SAMD cores

### ISSUE THREAD

**Issue by rEegLer** [4dsystems/Goldelox-Serial-Arduino-Library#7]
In Goldelox_Serial_4DLib.cpp file, it calls for non-Due boards to flush the virtual port however it causes hangs on all SAM/SAMD boards (e.g. Zero, MKR, M0, etc.). 

Currently it states this:

```
#ifndef _SAM3XA_
	// Only done on non Arduino Due Boards
	_virtualPort->flush();
#endif
```

Needs to be this:
```
#if !defined(ARDUINO_ARCH_SAMD) || (ARDUINO_ARCH_SAM)
	//Only done for non-SAMD/SAM architectures
	_virtualPort->flush();
#endif
```

**Comment by 4dsystems** [comment]
Thank you, this will be rolled out.

Regards
4D Systems
